# Generated by Django 4.1.7 on 2023-02-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=120, verbose_name='Task Name')),
                ('ue_Date', models.DateTimeField(verbose_name='Due_Date')),
                ('Status', models.BooleanField(default=False)),
                ('Description', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
