# Generated by Django 4.1.7 on 2023-02-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ue_Date',
            new_name='Due_Date',
        ),
    ]
