# Generated by Django 4.1.7 on 2023-02-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_ue_date_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Due_Date',
            field=models.DateField(verbose_name='Due_Date'),
        ),
    ]
