# Generated by Django 4.1.7 on 2023-02-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.BooleanField(choices=[(True, 'Complete'), (False, 'Not complete')], default=False, verbose_name='Status'),
        ),
    ]
