# Generated by Django 4.1.7 on 2023-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
    ]
